version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: quiz_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password          # ← 初期 root パス
      MYSQL_DATABASE: quiz                   # ← 自動生成される DB
      TZ: Asia/Tokyo                         # ローカルタイムゾーン
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
      - ./seed_python_quizzes.sql:/docker-entrypoint-initdb.d/seed_python.sql:ro
    healthcheck:                             # backend 起動待ち用
      test: ["CMD", "mysqladmin", "ping", "-ppassword", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

  backend:
    build: .
    container_name: quiz_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json:ro
      - /app/node_modules           
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data:
